---
- hosts: db
  become: yes
  vars:
    mysql_database: "webapp_db"
    mysql_user: "webapp_user"
    mysql_password: "suryraj1234"
  tasks:
    - name: update cache as apt-get update
      apt:
        update_cache: yes
    - name: install mysql and its dependencies
      apt:
        name: ['mysql-server', 'mysql-client', 'python3-mysqldb', 'libmysqlclient-dev']
        state: present
    - name: enable the service
      service:
        name: mysql
        state: started
        enabled: yes
    - name: Create MySQL database
      mysql_db:
        name: "{{ mysql_database }}"
        state: present
    - name: Create MySQL user
      mysql_user:
        name: "{{ mysql_user }}"
        password: "{{ mysql_password }}"
        priv: "{{ mysql_database }}.*:ALL"
        state: present
- hosts: web
  become: yes
  vars:
    app_repo_url: "/home/einfochips/Desktop/Day-17/project2/files/index.html"
    app_directory: "/var/www/html/"
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
    - name: Install Apache2
      apt:
        name: apache2
        state: present
    - name: Install PHP and extensions
      apt:
        name:
          - php
          - php-mysql
          - libapache2-mod-php
        state: present
    - name: Ensure Apache is started and enabled
      service:
        name: apache2
        state: started
        enabled: yes
    - name: Copy Web Application
      ansible.builtin.copy:
        src: "{{ app_repo_url }}"
        dest: "{{ app_directory }}"
    - name: Deploy Apache configuration file
      template:
        src: "/home/einfochips/Desktop/Day-17/project2/templates/apache_server.conf.j2"
        dest: "/etc/apache2/apache_server.conf"
        owner: root
        group: root
        mode: 0644
      notify:
        - Restart Apache
    - name: Ensure appropriate permissions for application directory
      file:
        path: "{{ app_directory }}"
        owner: www-data
        group: www-data
        state: directory
        recurse: yes
  handlers:
    - name: Restart Apache
      service:
        name: apache2
        state: restarted
