- hosts: all
  become: yes
  tasks:
    - name: Enabling Apache
      service:
        name: apache2
        enabled: yes

    - name: Starting Apache
      service:
        name: apache2
        state: started
