version: '3'
services:
  web1:
    image: nginx
    ports:
      - "8082:80"
    volumes:
      - shareddata:/usr/share/nginx/html
  web2:
    image: nginx
    ports:
      - "8083:80"
    volumes:
      - shareddata:/usr/share/nginx/html

volumes:
  shareddata:

